version: 2
jobs:
  build:
    docker:
      - image: circleci/node:6
    steps:
      - checkout
      - run:
          name: install dependencies
	  command: npm install
      - run:
          name: create bundle
	  command: npm run build
